name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}

    - name: Test
      run:
        ./millw __.test
